In [162]:
import pandas as pd

In [163]:
df = pd.read_csv('../data/origin/df_fraud_credit.csv', sep=",")

In [164]:
df.head()

,timestamp,sending_address,receiving_address,amount,transaction_type,location_region,ip_prefix,login_frequency,session_duration,purchase_pattern,age_group,risk_score,anomaly
0,1618185002,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,67435.0,transfer,Europe,192.000,3,48,focused,established,18.75,low_risk
1,1698642474,0xd6e251c23cbf52dbd472f079147873e655d8096f,0x51e8fbe24f124e0e30a614e14401b9bbfed5384c,1.0,purchase,South America,172.000,5,61,focused,established,25.0,low_risk
2,1619180066,0x2e0925b922fed01f6a85d213ae2718f54b8ca305,0x52c7911879f783d590af45bda0c0ef2b8536706f,66211.0,purchase,Asia,192.168,3,74,focused,established,31.25,low_risk
3,1591413882,0x93efefc25fcaf31d7695f28018d7a11ece55457f,0x8ac3b7bd531b3a833032f07d4e47c7af6ea7bace,14998.0,transfer,South America,172.000,8,111,high_value,veteran,36.75,low_risk
4,1611257295,0xad3b8de45d63f5cce28aef9a82cf30c397c6ceb9,0x6fdc047c2391615b3facd79b4588c7e9106e49f2,66002.0,sale,Africa,172.160,6,100,high_value,veteran,62.5,moderate_risk

In [165]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 13 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   timestamp          1048575 non-null  int64
 1   sending_address    1048575 non-null  str
 2   receiving_address  1048575 non-null  str
 3   amount             1048575 non-null  str
 4   transaction_type   1048575 non-null  str
 5   location_region    1048575 non-null  str
 6   ip_prefix          1048575 non-null  float64
 7   login_frequency    1048575 non-null  int64
 8   session_duration   1048575 non-null  int64
 9   purchase_pattern   1048575 non-null  str
 10  age_group          1048575 non-null  str
 11  risk_score         1048575 non-null  str
 12  anomaly            1048575 non-null  str
dtypes: float64(1), int64(3), str(9)
memory usage: 104.0 MB

In [166]:
df["transaction_type"].value_counts()

transaction_type
sale        334079
purchase    332692
transfer    295151
scam         52705
phishing     33948
Name: count, dtype: int64

In [167]:
df["location_region"].value_counts()

location_region
North America    210145
Europe           209749
Asia             208742
South America    207821
Africa           206323
0                  5795
Name: count, dtype: int64

In [168]:
df["age_group"].value_counts()

age_group
veteran        352576
new            348775
established    347224
Name: count, dtype: int64

In [169]:
df[df["amount"].str.strip().str.lower() == "none"] = None

In [170]:
df["amount"] = df["amount"].astype(float)

In [171]:
df["amount"].isna().sum()

np.int64(5641)

In [172]:
df.columns

Index(['timestamp', 'sending_address', 'receiving_address', 'amount',
       'transaction_type', 'location_region', 'ip_prefix', 'login_frequency',
       'session_duration', 'purchase_pattern', 'age_group', 'risk_score',
       'anomaly'],
      dtype='str')

In [173]:
# df.dropna(subset=["sending_address", "receiving_address"], inplace=True)

In [174]:
df.shape

(1048575, 13)

In [175]:
df.head()

,timestamp,sending_address,receiving_address,amount,transaction_type,location_region,ip_prefix,login_frequency,session_duration,purchase_pattern,age_group,risk_score,anomaly
0,1.618185e+09,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,67435.0,transfer,Europe,192.000,3.0,48.0,focused,established,18.75,low_risk
1,1.698642e+09,0xd6e251c23cbf52dbd472f079147873e655d8096f,0x51e8fbe24f124e0e30a614e14401b9bbfed5384c,1.0,purchase,South America,172.000,5.0,61.0,focused,established,25.0,low_risk
2,1.619180e+09,0x2e0925b922fed01f6a85d213ae2718f54b8ca305,0x52c7911879f783d590af45bda0c0ef2b8536706f,66211.0,purchase,Asia,192.168,3.0,74.0,focused,established,31.25,low_risk
3,1.591414e+09,0x93efefc25fcaf31d7695f28018d7a11ece55457f,0x8ac3b7bd531b3a833032f07d4e47c7af6ea7bace,14998.0,transfer,South America,172.000,8.0,111.0,high_value,veteran,36.75,low_risk
4,1.611257e+09,0xad3b8de45d63f5cce28aef9a82cf30c397c6ceb9,0x6fdc047c2391615b3facd79b4588c7e9106e49f2,66002.0,sale,Africa,172.160,6.0,100.0,high_value,veteran,62.5,moderate_risk

In [176]:
df["transaction_datetime"] = pd.to_datetime(df["timestamp"], unit="s")

In [177]:
df.head()

,timestamp,sending_address,receiving_address,amount,transaction_type,location_region,ip_prefix,login_frequency,session_duration,purchase_pattern,age_group,risk_score,anomaly,transaction_datetime
0,1.618185e+09,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,67435.0,transfer,Europe,192.000,3.0,48.0,focused,established,18.75,low_risk,2021-04-11 23:50:02
1,1.698642e+09,0xd6e251c23cbf52dbd472f079147873e655d8096f,0x51e8fbe24f124e0e30a614e14401b9bbfed5384c,1.0,purchase,South America,172.000,5.0,61.0,focused,established,25.0,low_risk,2023-10-30 05:07:54
2,1.619180e+09,0x2e0925b922fed01f6a85d213ae2718f54b8ca305,0x52c7911879f783d590af45bda0c0ef2b8536706f,66211.0,purchase,Asia,192.168,3.0,74.0,focused,established,31.25,low_risk,2021-04-23 12:14:26
3,1.591414e+09,0x93efefc25fcaf31d7695f28018d7a11ece55457f,0x8ac3b7bd531b3a833032f07d4e47c7af6ea7bace,14998.0,transfer,South America,172.000,8.0,111.0,high_value,veteran,36.75,low_risk,2020-06-06 03:24:42
4,1.611257e+09,0xad3b8de45d63f5cce28aef9a82cf30c397c6ceb9,0x6fdc047c2391615b3facd79b4588c7e9106e49f2,66002.0,sale,Africa,172.160,6.0,100.0,high_value,veteran,62.5,moderate_risk,2021-01-21 19:28:15

In [178]:
df.drop(columns=["timestamp"], inplace=True)

In [179]:
df.head()

,sending_address,receiving_address,amount,transaction_type,location_region,ip_prefix,login_frequency,session_duration,purchase_pattern,age_group,risk_score,anomaly,transaction_datetime
0,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,67435.0,transfer,Europe,192.000,3.0,48.0,focused,established,18.75,low_risk,2021-04-11 23:50:02
1,0xd6e251c23cbf52dbd472f079147873e655d8096f,0x51e8fbe24f124e0e30a614e14401b9bbfed5384c,1.0,purchase,South America,172.000,5.0,61.0,focused,established,25.0,low_risk,2023-10-30 05:07:54
2,0x2e0925b922fed01f6a85d213ae2718f54b8ca305,0x52c7911879f783d590af45bda0c0ef2b8536706f,66211.0,purchase,Asia,192.168,3.0,74.0,focused,established,31.25,low_risk,2021-04-23 12:14:26
3,0x93efefc25fcaf31d7695f28018d7a11ece55457f,0x8ac3b7bd531b3a833032f07d4e47c7af6ea7bace,14998.0,transfer,South America,172.000,8.0,111.0,high_value,veteran,36.75,low_risk,2020-06-06 03:24:42
4,0xad3b8de45d63f5cce28aef9a82cf30c397c6ceb9,0x6fdc047c2391615b3facd79b4588c7e9106e49f2,66002.0,sale,Africa,172.160,6.0,100.0,high_value,veteran,62.5,moderate_risk,2021-01-21 19:28:15

In [180]:
df[df["amount"] < 0]

Empty DataFrame
Columns: [sending_address, receiving_address, amount, transaction_type, location_region, ip_prefix, login_frequency, session_duration, purchase_pattern, age_group, risk_score, anomaly, transaction_datetime]
Index: []

In [181]:
df.columns

Index(['sending_address', 'receiving_address', 'amount', 'transaction_type',
       'location_region', 'ip_prefix', 'login_frequency', 'session_duration',
       'purchase_pattern', 'age_group', 'risk_score', 'anomaly',
       'transaction_datetime'],
      dtype='str')

In [182]:
df[df.duplicated(keep=False)]

,sending_address,receiving_address,amount,transaction_type,location_region,ip_prefix,login_frequency,session_duration,purchase_pattern,age_group,risk_score,anomaly,transaction_datetime
458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1047803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1047825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1048006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1048137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1048219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [183]:
df.head()

,sending_address,receiving_address,amount,transaction_type,location_region,ip_prefix,login_frequency,session_duration,purchase_pattern,age_group,risk_score,anomaly,transaction_datetime
0,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,67435.0,transfer,Europe,192.000,3.0,48.0,focused,established,18.75,low_risk,2021-04-11 23:50:02
1,0xd6e251c23cbf52dbd472f079147873e655d8096f,0x51e8fbe24f124e0e30a614e14401b9bbfed5384c,1.0,purchase,South America,172.000,5.0,61.0,focused,established,25.0,low_risk,2023-10-30 05:07:54
2,0x2e0925b922fed01f6a85d213ae2718f54b8ca305,0x52c7911879f783d590af45bda0c0ef2b8536706f,66211.0,purchase,Asia,192.168,3.0,74.0,focused,established,31.25,low_risk,2021-04-23 12:14:26
3,0x93efefc25fcaf31d7695f28018d7a11ece55457f,0x8ac3b7bd531b3a833032f07d4e47c7af6ea7bace,14998.0,transfer,South America,172.000,8.0,111.0,high_value,veteran,36.75,low_risk,2020-06-06 03:24:42
4,0xad3b8de45d63f5cce28aef9a82cf30c397c6ceb9,0x6fdc047c2391615b3facd79b4588c7e9106e49f2,66002.0,sale,Africa,172.160,6.0,100.0,high_value,veteran,62.5,moderate_risk,2021-01-21 19:28:15

In [184]:
df.columns

Index(['sending_address', 'receiving_address', 'amount', 'transaction_type',
       'location_region', 'ip_prefix', 'login_frequency', 'session_duration',
       'purchase_pattern', 'age_group', 'risk_score', 'anomaly',
       'transaction_datetime'],
      dtype='str')

In [185]:
str_columns = [
    "sending_address",
    "receiving_address",
    "transaction_type",
    "location_region",
    "ip_prefix",
    "purchase_pattern",
    "age_group",
    "anomaly"
]

for col in str_columns:
    df[df[col].isin(["none", "null", "n/a", ""])] = None

In [186]:
df[df[str_columns].isna().any(axis=1)]

,sending_address,receiving_address,amount,transaction_type,location_region,ip_prefix,login_frequency,session_duration,purchase_pattern,age_group,risk_score,anomaly,transaction_datetime
458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1047803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1047825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1048006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1048137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1048219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [187]:
df["risk_score"] = pd.to_numeric(df["risk_score"], errors="coerce")

In [188]:
df[df["risk_score"] > 100]

Empty DataFrame
Columns: [sending_address, receiving_address, amount, transaction_type, location_region, ip_prefix, login_frequency, session_duration, purchase_pattern, age_group, risk_score, anomaly, transaction_datetime]
Index: []

In [189]:
df[df["risk_score"].isna()]

,sending_address,receiving_address,amount,transaction_type,location_region,ip_prefix,login_frequency,session_duration,purchase_pattern,age_group,risk_score,anomaly,transaction_datetime
12,0xfcf9a3467d3d93688fb17b4ebb6b681b1fa29f94,0x6d4f7db757a1bd6bb43029ee13c037651ca20c74,65319.0,purchase,North America,172.16,4.0,62.0,focused,established,NaN,low_risk,2020-05-21 07:08:13
13,0xd2cff98e8e707049db92500414fec6f0bb5c895c,0x2e0925b922fed01f6a85d213ae2718f54b8ca305,67174.0,purchase,South America,192.00,2.0,38.0,random,new,NaN,low_risk,2022-08-26 21:46:24
21,0xddbe1291b454f9b8699220f1e8724aa641ef4b42,0x51c0d24ccc5d9b0dd793052cb2d41efde2568056,15462.0,sale,Africa,172.00,6.0,144.0,high_value,veteran,NaN,low_risk,2022-12-03 05:38:00
81,0xffa670245089044b1e355508a7843692a25a5e52,0xdce371e2762ac4250469f709c5b766e754e2c9a2,59980.0,purchase,Asia,10.00,1.0,38.0,random,new,NaN,low_risk,2022-11-25 19:02:27
301,0x4976201c394fa2b954bc71953b4d2482054874e3,0x296a2c7ab863e0d414da20c8bb6ec1fdc09efda3,13363.0,transfer,South America,172.16,4.0,78.0,focused,established,NaN,low_risk,2020-02-25 00:04:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1048219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1048288,0x60e69251a33fe222ea67c6f5769cb803ebb9c77c,0xbc9bc0162fe1ef6624c4f9ea0139576e7407a99d,56600.0,sale,Asia,172.00,7.0,141.0,high_value,veteran,NaN,low_risk,2022-06-03 12:54:25
1048340,0x48a01986b2d20dc02ae4e7fc2d97941d17ee0248,0x3062bb340d09613209c92c051de077c782a32d21,20025.0,transfer,North America,192.00,1.0,36.0,random,new,NaN,low_risk,2020-01-31 15:10:09
1048393,0xd620eeb117bf8e6ebfb7c8d0df00583a1d72fe43,0xd6fc559bedfab086e68a2637ac3f56287c3dcdcc,74548.0,sale,Europe,192.00,8.0,98.0,high_value,veteran,NaN,moderate_risk,2023-09-05 15:40:58

In [190]:
df.isna().sum()

sending_address          5641
receiving_address        5641
amount                   5641
transaction_type         5641
location_region          5641
ip_prefix                5641
login_frequency          5641
session_duration         5641
purchase_pattern         5641
age_group                5641
risk_score              11308
anomaly                  5641
transaction_datetime     5641
dtype: int64

In [191]:
df.dropna(subset=["sending_address", "receiving_address"], inplace=True)

In [192]:
df.isna().sum()

sending_address            0
receiving_address          0
amount                     0
transaction_type           0
location_region            0
ip_prefix                  0
login_frequency            0
session_duration           0
purchase_pattern           0
age_group                  0
risk_score              5667
anomaly                    0
transaction_datetime       0
dtype: int64

In [193]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[
    df.duplicated(
        subset=[
            "sending_address",
            "receiving_address"
        ],
        keep=False
    )
]

,sending_address,receiving_address,amount,transaction_type,location_region,ip_prefix,login_frequency,session_duration,purchase_pattern,age_group,risk_score,anomaly,transaction_datetime
0,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,67435.0,transfer,Europe,192.000,3.0,48.0,focused,established,18.7500,low_risk,2021-04-11 23:50:02
1,0xd6e251c23cbf52dbd472f079147873e655d8096f,0x51e8fbe24f124e0e30a614e14401b9bbfed5384c,1.0,purchase,South America,172.000,5.0,61.0,focused,established,25.0000,low_risk,2023-10-30 05:07:54
2,0x2e0925b922fed01f6a85d213ae2718f54b8ca305,0x52c7911879f783d590af45bda0c0ef2b8536706f,66211.0,purchase,Asia,192.168,3.0,74.0,focused,established,31.2500,low_risk,2021-04-23 12:14:26
3,0x93efefc25fcaf31d7695f28018d7a11ece55457f,0x8ac3b7bd531b3a833032f07d4e47c7af6ea7bace,14998.0,transfer,South America,172.000,8.0,111.0,high_value,veteran,36.7500,low_risk,2020-06-06 03:24:42
4,0xad3b8de45d63f5cce28aef9a82cf30c397c6ceb9,0x6fdc047c2391615b3facd79b4588c7e9106e49f2,66002.0,sale,Africa,172.160,6.0,100.0,high_value,veteran,62.5000,moderate_risk,2021-01-21 19:28:15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,0xc4f5d6d031cba61e837c43c5d5f9f27005017bfd,0x43551a7291436ea55bc2fa8cf5a593408c1c38cf,74339.0,sale,Africa,172.000,7.0,84.0,high_value,veteran,62.5000,moderate_risk,2021-01-16 22:35:04
1048571,0xc028752d06eb95cdd6a708346ba0849e2495fc3d,0x2c66467afe153987ff882c4edc2020a0c041cc0d,74785.0,purchase,Asia,10.000,4.0,57.0,focused,established,42.1875,low_risk,2021-06-18 01:05:53
1048572,0xe3a75298a17d6e04d2bd819f9ead13bbc87b110b,0xf113ab890bc550a237110a776aa1b10ee9d91704,6843.0,transfer,South America,10.000,8.0,153.0,high_value,veteran,35.0000,low_risk,2020-06-28 03:05:19
1048573,0x6a341efbef4e656e62c4164324aeb6ebfb6f1502,0x2039d649d1cf690a7161e8cbff11c6f14e70ffa0,20931.0,transfer,Africa,192.000,7.0,144.0,high_value,veteran,36.7500,low_risk,2023-04-11 01:35:48
1048574,0xdb53cb7e6d171afff8201f72ec4ce4811fe507a8,0x91f9800a9869e0b83a63f73f08700ecffabdf427,41634.0,purchase,North America,192.168,2.0,26.0,random,new,49.6125,low_risk,2023-01-25 17:13:23

In [200]:
df[
    (df["sending_address"] == "0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da") &
    (df["receiving_address"] == "0x39f82e1c09bc6d7baccc1e79e5621ff812f50572")
]

,sending_address,receiving_address,amount,transaction_type,location_region,ip_prefix,login_frequency,session_duration,purchase_pattern,age_group,risk_score,anomaly,transaction_datetime
0,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,67435.0,transfer,Europe,192.000,3.0,48.0,focused,established,18.7500,low_risk,2021-04-11 23:50:02
2710,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,5334.0,transfer,Asia,172.000,8.0,136.0,high_value,veteran,35.0000,low_risk,2021-03-09 20:37:04
5420,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,17234.0,transfer,Europe,172.160,2.0,37.0,random,new,35.4375,low_risk,2022-02-17 15:52:22
8130,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,29096.0,sale,Asia,10.000,8.0,86.0,high_value,veteran,52.5000,low_risk,2022-08-11 03:13:31
10840,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,37916.0,sale,Europe,192.000,8.0,92.0,high_value,veteran,52.5000,low_risk,2020-12-25 07:44:22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1035384,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,71248.0,transfer,South America,172.160,6.0,101.0,high_value,veteran,43.7500,low_risk,2023-06-21 19:20:44
1038094,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,31953.0,sale,South America,192.168,7.0,150.0,high_value,veteran,52.5000,low_risk,2022-01-08 20:07:10
1040804,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,55626.0,sale,Asia,172.160,1.0,37.0,random,new,56.7000,low_risk,2022-11-22 17:04:29
1043514,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,23484.0,sale,Africa,10.000,6.0,132.0,high_value,veteran,52.5000,low_risk,2020-03-03 17:52:42
1046224,0x9d32d0bf2c00f41ce7ca01b66e174cc4dcb0c1da,0x39f82e1c09bc6d7baccc1e79e5621ff812f50572,21822.0,purchase,Europe,192.168,4.0,67.0,focused,established,26.2500,low_risk,2021-11-03 03:20:37